export const catImgs: { [key: string]: any } = {
	ecology: require("@assets/images/categories/ecology.png"),
	sport: require("@assets/images/categories/sport.png"),
	manage_budget: require("@assets/images/categories/manage_budget.png"),
	food: require("@assets/images/categories/food.png"),
	productivity: require("@assets/images/categories/productivity.png"),
	develop_skill: require("@assets/images/categories/develop_skill.png"),
	well_being: require("@assets/images/categories/well_being.png"),
	mental_health: require("@assets/images/categories/mental_health.png"),
	housework: require("@assets/images/categories/housework.png"),
	social_life: require("@assets/images/categories/social_life.png"),
	creativity: require("@assets/images/categories/creativity.png"),
	grow: require("@assets/images/categories/grow.png"),
	spirituality: require("@assets/images/categories/spirituality.png"),
	auto_sabotage: require("@assets/images/categories/auto_sabotage.png"),
	addictions: require("@assets/images/categories/addictions.png"),
	mauvaise_alimentation: require("@assets/images/categories/mauvaise_alimentation.png"),
	procrastination: require("@assets/images/categories/procrastination.png"),
	gestion_temps: require("@assets/images/categories/gestion_temps.png"),
	perfectionnisme: require("@assets/images/categories/perfectionnisme.png"),
	sommeil: require("@assets/images/categories/sommeil.png"),
	dependance_ecrans: require("@assets/images/categories/dependance_ecrans.png"),
};
